0503최단경로제출
Altu-Bitu-2/Altu-Bitu-2-hello pull request #14
Opened 2022-05-08 18:49 UTC by hello0U0

#### 내용 & 질문
>

#### <기존 제출>
> 1504, 1719, 1865, 10282, 11559, 18111, 프로그래머스-합승 택시 요금

#### <추가제출>
>

2022-05-09 03:15 UTC, bsa0322 requested changes
p1. 효정님 안녕하세요 😊😊 항상 과제 제출도 빠르시고, 코드 구현 능력도 너무 좋으셔서 감탄하고 가네요! 이번 과제도 너무 잘 해주셨어요 😍 10282.cpp가 파일이 잘못 올라온 것 같은데 확인 부탁드립니다! 소소한 코멘트 정도 남겼어요. 뿌요뿌요 문제는 조금 더 리팩토링할 수 있을 것 같아서 코멘트 남겼으니 코멘트에 대해 질문 있으시면 남겨주세요! 질문하실 때나 수정하신 후, 다시 리뷰어로 호출해주세요~! 과제하시느라 수고하셨습니다 🥰

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/11559.cpp
> +		for (int k = 0; k < xcnt; k++) nowfield[j--][i] = '.';
기존의 poyofield를 계속 사용하려 하니 인덱스 관리가 조금 복잡해지네요! 아예 새로운 필드를 만들어서 덮어씌워주는 건 어떨까요? 그렇게 하면 'x'의 사용 없이도 바로 뿌요를 '.'으로 지워서 관리해줄 수 있을 것 같아요!

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/1504.cpp
> +	int ans2 = one_v2 + v1_v2 + v1_n;	//1 -> v2 -> v1 -> n
p2. 정확히 3개의 연산이 시작 정점을 제외하고 같이 일어나고 있어요! 이렇게 따로 적어주신 것도 좋지만, 반복되는 연산을 더 편하게 처리할 수 있는 방법을 사용해도 좋을 것 같아요!

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/1504.cpp
> +	return ans1 < ans2 ? ans1 : ans2;
p2. 최단 경로는 경로가 가장 짧은 것을 결정하죠! 그리고 저희는 경로의 초기값을 모두 INF로 해주고 있어요. 그렇다면 경로가 없는 경우는 INF보다 항상 큰 경우이니 이렇게 따로따로 고려하지 않고 한 번에 고려하면 가독성이 더 높아질 것 같습니다! 최단 경로는 어차피 **min** 값을 구하는 것이니 경로가 없는 경우는 고려하지 않아도 괜찮아요. 그렇다면 아예 경로가 하나도 없는 경우만 잘 체크해주면 되겠죠 😊

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/1719.cpp
> +					direct[i][j].first = direct[i][k].first;
좋아요~~! direct[i][k]의 경로를 저장해주어야 한다는 걸 아주 잘 캐치해주셨어요! 😍

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/1719.cpp
> +			cout << (i == j ? "-" : to_string(direct[i][j].first)) << " ";
p3. c++의 삼항 연산자는 문자열 형태만 가능해서 to_string으로 변환하는 과정이 필요하네요! 출력을 위한 형 변환이라, 잘 모르는 사람이 봤을 때는 가독성이 떨어질 수 있으니 아예 if조건문으로 출력을 분리해도 좋을 것 같아요~!

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/18111.cpp
> +	return time;
로직 완벽해요!! 아주 좋아요~~! 😍

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/1865.cpp
> +		}
사실 원래라면 출발 지점을 모두 돌아서 검사할 경우 시간 복잡도가 O(n) * O(ne)로 500^2 * 5200 = 13*10^8 으로 시간초과가 납니다! 그런데 해당 문제의 테스트 케이스가 약해서 통과가 되는 것 같아요. 아래 질문 글 참고해주시면 좋을 것 같아요 😊😊
https://www.acmicpc.net/board/view/72995

2022-05-09 03:15 UTC, bsa0322 commented on 05월 03일 - 최단경로/programmers_level3_taxi.cpp
> +        if (nowpath < answer) answer = nowpath;
p3. 라이브러리를 사용해주면 더 간단하게 구현할 수 있을 것 같아요! 😊

2022-05-09 15:27 UTC, hello0U0 commented
> 10282 수정했습니다.
> 11559 
> > p3. 변수 명 수정했습니다.
> > p3. chain을 필요할 때 생성하는 것으로 바꿨습니다.
> > p3. 수정했습니다.
> > p1. queue를 이용한 bfs로 바꿨습니다.
> > p2. visited 방문배열을 사용하도록 바꿨습니다.
> 1504
> > p2. 수정했습니다.
> > p2. INF를 바꿨습니다.
> 1719
> > p3. if문으로 바꿨습니다.
> programmers_level3_taxi 
> > p3.algorithm을 사용했습니다.

2022-05-10 15:05 UTC, bsa0322 commented on 05월 03일 - 최단경로/11559.cpp
> +		else break;
p2. 가독성 관련한 코멘트인데요! 종료 조건을 반대로 설정해주면, 인덴테이션도 줄이고, else문 사용도 줄일 수 있을 것 같아요! 😊

2022-05-16 00:45 UTC, merged